- direction: GZ_TO_ROS
  gz_topic_name: /imu/data
  gz_type_name: gz.msgs.IMU
  ros_topic_name: /imu/data
  ros_type_name: sensor_msgs/msg/Imu
- direction: GZ_TO_ROS
  gz_topic_name: /main_camera/image
  gz_type_name: gz.msgs.Image
  ros_topic_name: /main_camera/image
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /main_camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_topic_name: /main_camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
- direction: GZ_TO_ROS
  gz_topic_name: /main_camera/depth_image
  gz_type_name: gz.msgs.Image
  ros_topic_name: /main_camera/depth_image
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /main_camera/points
  gz_type_name: gz.msgs.PointCloudPacked
  ros_topic_name: /main_camera/points
  ros_type_name: sensor_msgs/msg/PointCloud2
- direction: GZ_TO_ROS
  gz_topic_name: /model/space_cobot/pose
  gz_type_name: gz.msgs.Pose
  ros_topic_name: /cobot_gz/poses
  ros_type_name: geometry_msgs/msg/PoseStamped
- direction: ROS_TO_GZ
  gz_topic_name: /model/space_cobot/cmd_vel
  gz_type_name: gz.msgs.Twist
  ros_topic_name: /space_cobot/cmd_vel_world
  ros_type_name: geometry_msgs/msg/Twist
- direction: ROS_TO_GZ
  gz_topic_name: /world/default/wrench/persistent
  gz_type_name: gz.msgs.EntityWrench
  ros_topic_name: /world/default/wrench/persistent
  ros_type_name: ros_gz_interfaces/msg/EntityWrench
- direction: GZ_TO_ROS
  gz_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
