# Example parameter file, see parameters_launch.py

# Format is namespace_name/node_name
my_camera/gscam_publisher:
    ros__parameters:
        gscam_config: "nvarguscamerasrc sensor-id=0 ! video/x-raw(memory:NVMM), width=1920, height=1080, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2 ! video/x-raw, format=(string)BGRx ! videoconvert"
        preroll: False
        use_gst_timestamps: False
        frame_id: "my_camera_frame"
