scobot:
  ERLE_UID: 1001 #erle user id   

  gains:
    position:
      proportional: #default: all at 20
        KXP_x: 20.0
        KXP_y: 20.0
        KXP_z: 20.0
      derivative: #default: all at 22
        KXD_x: 22.0
        KXD_y: 22.0
        KXD_z: 22.0
    attitude:
      proportional: #default: all at 0.1
        Kang_x: 0.1
        Kang_y: 0.2
        Kang_z: 0.1
      derivative: #default: all at 0.1510
        Komg_x: 0.1510  
        Komg_y: 0.05 
        Komg_z: 0.1510

  constraints:                   
    MAX_LIN_VEL: 1.0 #m/s      
    MAX_ANG_VEL: 6.2831853072 #2*pi rad/s
    MIN_LIN_VEL: -1.0 #m/s    
    MIN_ANG_VEL: -6.2831853072 #2*pi rad/s              
    MAX_X: 1000.0       
    MAX_Y: 1000.0       
    MAX_Z: 1000.0       
    MIN_X: -1000.0      
    MIN_Y: -1000.0      
    MIN_Z: -1000.0
    CSV_DEBUG: 1.0
    ROS_DEBUG: 1.0

  commands:
    armed: 0.0

#  gain_vectors:
#    PosP: [20.0,    20.0,   20.0]   #KXp 
#    PosD: [22.0,    22.0,   22.0]   #KXd
#    AttP: [0.1,     0.1,    0.1]    #K_ang
#    AttD: [0.1510,  0.1510, 0.1510] #K_omg 